title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: LeafBrightDay

plugins:
 - jekyll-feed
 - jekyll-seo-tag

google_analytics: UA-NNNNNNNN-N
